/** @type {import('tailwindcss').Config} */
export default {
  content: [
    "./index.html",
    "./src/**/*.{js,ts,jsx,tsx}",
  ],
  darkMode: 'class',
  theme: {
    extend: {
      colors: {
        'primary': '#ddb7ff',
        'on-primary': '#490080',
        'primary-container': '#b76dff',
        'on-primary-container': '#400071',
        'inverse-primary': '#842bd2',
        'primary-fixed': '#f0dbff',
        'primary-fixed-dim': '#ddb7ff',
        'on-primary-fixed': '#2c0051',
        'on-primary-fixed-variant': '#6900b3',
        'secondary': '#7bd0ff',
        'on-secondary': '#00354a',
        'secondary-container': '#00a6e0',
        'on-secondary-container': '#00374d',
        'secondary-fixed': '#c4e7ff',
        'secondary-fixed-dim': '#7bd0ff',
        'on-secondary-fixed': '#001e2c',
        'on-secondary-fixed-variant': '#004c69',
        'tertiary': '#d2bbff',
        'on-tertiary': '#3f008e',
        'tertiary-container': '#a476ff',
        'on-tertiary-container': '#36007d',
        'tertiary-fixed': '#eaddff',
        'tertiary-fixed-dim': '#d2bbff',
        'on-tertiary-fixed': '#25005a',
        'on-tertiary-fixed-variant': '#5a00c6',
        'surface': '#0f131d',
        'surface-dim': '#0f131d',
        'surface-bright': '#353944',
        'surface-container-lowest': '#0a0e18',
        'surface-container-low': '#171b26',
        'surface-container': '#1c1f2a',
        'surface-container-high': '#262a35',
        'surface-container-highest': '#313540',
        'surface-variant': '#313540',
        'on-surface': '#dfe2f1',
        'on-surface-variant': '#cfc2d6',
        'inverse-surface': '#dfe2f1',
        'inverse-on-surface': '#2c303b',
        'outline': '#988d9f',
        'outline-variant': '#4d4354',
        'surface-tint': '#ddb7ff',
        'background': '#0f131d',
        'on-background': '#dfe2f1',
        'error': '#ffb4ab',
        'on-error': '#690005',
        'error-container': '#93000a',
        'on-error-container': '#ffdad6',
      },
      fontFamily: {
        'display': ['Space Grotesk', 'sans-serif'],
        'headline': ['Space Grotesk', 'sans-serif'],
        'body': ['Geist', 'sans-serif'],
        'mono': ['JetBrains Mono', 'monospace'],
        'display-lg': ['Space Grotesk', 'sans-serif'],
        'display-md': ['Space Grotesk', 'sans-serif'],
        'headline-lg': ['Space Grotesk', 'sans-serif'],
        'headline-md': ['Space Grotesk', 'sans-serif'],
        'headline-sm': ['Space Grotesk', 'sans-serif'],
        'body-lg': ['Geist', 'sans-serif'],
        'body-md': ['Geist', 'sans-serif'],
        'body-sm': ['Geist', 'sans-serif'],
        'telemetry-data': ['JetBrains Mono', 'monospace'],
        'label-caps': ['JetBrains Mono', 'monospace'],
        'label-code': ['JetBrains Mono', 'monospace'],
      },
      spacing: {
        'space-xs': '0.25rem',
        'space-sm': '0.5rem',
        'space-md': '1rem',
        'space-lg': '1.5rem',
        'space-xl': '2.5rem',
        'gutter': '1.5rem',
        'gutter-mobile': '0.75rem',
        'margin': '2rem',
        'margin-mobile': '1rem',
      },
      borderRadius: {
        'DEFAULT': '0.5rem',
        'sm': '0.25rem',
        'md': '0.75rem',
        'lg': '1rem',
        'xl': '1.5rem',
        'full': '9999px',
      },
      boxShadow: {
        'glow-primary': '0 0 24px -2px rgba(183, 109, 255, 0.45)',
        'glow-secondary': '0 0 24px -2px rgba(123, 208, 255, 0.45)',
        'hud-card': '0 20px 60px rgba(0, 0, 0, 0.8)',
      },
      animation: {
        'pulse-slow': 'pulse 3s cubic-bezier(0.4, 0, 0.6, 1) infinite',
        'glow': 'glow 2s ease-in-out infinite alternate',
      },
      keyframes: {
        glow: {
          '0%': { boxShadow: '0 0 15px rgba(183,109,255,0.4)' },
          '100%': { boxShadow: '0 0 30px rgba(183,109,255,0.8)' },
        }
      }
    },
  },
  plugins: [],
}
